export const arabicDisplayLabels: Record<string, string> = {
  active: 'نشط',
  advance: 'سلفة',
  admin_withdrawal: 'سحب إداري',
  all_branches: 'جميع الفروع',
  approved: 'معتمدة',
  bank: 'بنكي',
  cancelled: 'ملغاة',
  cash: 'نقدي',
  closed: 'مغلقة',
  completed: 'مكتمل',
  daily_cash_sales: 'مبيعات يومية نقدية',
  daily_sale: 'مبيعات يومية',
  daily_sale_vault_transfer: 'تحويل مبيعات يومية إلى الخزنة',
  daily_sales_closing_delivery: 'إغلاق مبيعات التوصيل',
  daily_sales_closing_in_store_card: 'إغلاق مبيعات البطاقة',
  daily_sales_closing_vault_transfer: 'تحويل إغلاق يومي إلى الخزنة',
  daily_sales_closing_website_bank: 'إغلاق مبيعات الموقع البنكية',
  daily_sales_closing_website_cash: 'إغلاق مبيعات الموقع النقدية',
  debt: 'دين',
  deposit: 'إيداع',
  deposit_from_bank: 'إيداع من البنك',
  deposit_from_drawer: 'إيداع من الدرج',
  deposit_from_vault: 'إيداع من الخزنة',
  draft: 'مسودة',
  employee_advance: 'سلفة موظف',
  employee_advance_bank: 'سلفة موظف بنكية',
  employee_advance_cash: 'سلفة موظف نقدية',
  employee_debt: 'دين موظف',
  employee_debt_bank: 'دين موظف بنكي',
  employee_debt_cash: 'دين موظف نقدي',
  employee_obligation_repayment: 'سداد التزام موظف',
  employee_obligation_repayment_bank: 'سداد التزام موظف بنكي',
  employee_obligation_repayment_cash: 'سداد التزام موظف نقدي',
  employee_obligation_reversal_bank: 'عكس التزام موظف بنكي',
  employee_obligation_reversal_cash: 'عكس التزام موظف نقدي',
  expense: 'مصروف',
  expense_bank: 'مصروف بنكي',
  expense_bank_reversal: 'عكس مصروف بنكي',
  expense_cash: 'مصروف نقدي',
  expense_cash_reversal: 'عكس مصروف نقدي',
  expense_payment: 'دفع مصروف',
  expense_reversal: 'عكس مصروف',
  expense_vault_reversal: 'عكس مصروف من الخزنة',
  financial_reversal: 'عكس مالي',
  financial_penalty: 'غرامة مالية',
  in: 'داخل',
  incoming: 'داخل',
  manual_deposit: 'إيداع يدوي',
  manual_withdrawal: 'سحب يدوي',
  open: 'مفتوحة',
  other: 'أخرى',
  out: 'خارج',
  outgoing: 'خارج',
  paid: 'مدفوعة',
  partially_paid: 'مدفوعة جزئيا',
  partially_recovered: 'مستردة جزئيا',
  payroll_payment: 'صرف راتب',
  payroll_payment_bank: 'صرف راتب بنكي',
  payroll_payment_cash: 'صرف راتب نقدي',
  payroll_vault_reversal: 'عكس صرف راتب من الخزنة',
  purchase_invoice_payment: 'دفع فاتورة شراء',
  reopened: 'مفتوحة للتعديل',
  refund_bank: 'مرتجع بنكي',
  sales_receipt_bank: 'قبض مبيعات بنكي',
  sales_return_cash: 'مرتجع نقدي',
  settled: 'مسددة',
  settlement: 'تسوية',
  single_branch: 'فرع واحد',
  stock_count: 'جرد مخزون',
  supplier_payment: 'دفعة مورد',
  supplier_payment_bank: 'دفعة مورد بنكية',
  supplier_payment_bank_reversal: 'عكس دفعة مورد بنكية',
  supplier_payment_cash: 'دفعة مورد نقدية',
  supplier_payment_cash_reversal: 'عكس دفعة مورد نقدية',
  transfer: 'تحويل',
  transfer_to_vault: 'تحويل إلى الخزنة',
  unpaid: 'غير مدفوعة',
  vault: 'خزنة',
  withdrawal: 'سحب',
  withdrawal_to_bank: 'تحويل إلى البنك',
  withdrawal_to_vault: 'تحويل إلى الخزنة',
  wholesale_sales_cash_collection: 'تحصيل بيع جملة نقدي',
  wholesale_sales_payment: 'تحصيل بيع جملة',
  wholesale_sales_receipt_bank: 'تحصيل بيع جملة بنكي',
};

export function displayLabel(value?: string | boolean | null, fallback = 'غير محدد') {
  if (typeof value === 'boolean') return value ? 'نشط' : 'متوقف';
  const normalized = value?.trim();
  if (!normalized) return fallback;
  if (arabicDisplayLabels[normalized]) return arabicDisplayLabels[normalized];
  return /^[a-z0-9_/-]+$/.test(normalized) ? fallback : normalized;
}
