import type { SettingGroup } from '../components/settings-center-form';

export const defaultSettingGroups: SettingGroup[] = [
  {
    key: 'general',
    title: 'الإعدادات العامة',
    description: 'هوية النظام ومعلومات الشركة الأساسية التي تظهر في الواجهة والتقارير.',
    fields: [
      { key: 'appName', label: 'اسم البرنامج', type: 'text', value: 'Restaurant ERP', defaultValue: 'Restaurant ERP', note: null, options: null, min: null, max: null },
      { key: 'systemDescription', label: 'وصف النظام', type: 'textarea', value: 'نظام إدارة مطاعم متكامل', defaultValue: 'نظام إدارة مطاعم متكامل', note: null, options: null, min: null, max: null },
      { key: 'companyName', label: 'اسم الشركة', type: 'text', value: '', defaultValue: '', note: null, options: null, min: null, max: null },
      { key: 'phone', label: 'الهاتف', type: 'text', value: '', defaultValue: '', note: null, options: null, min: null, max: null },
      { key: 'email', label: 'البريد الإلكتروني', type: 'email', value: '', defaultValue: '', note: null, options: null, min: null, max: null },
      { key: 'address', label: 'العنوان', type: 'textarea', value: '', defaultValue: '', note: null, options: null, min: null, max: null },
      { key: 'logoUrl', label: 'اللوغو', type: 'url', value: '', defaultValue: '', note: 'ضع رابط صورة اللوغو أو مسارها داخل النظام.', options: null, min: null, max: null },
    ],
  },
  {
    key: 'appearance',
    title: 'المظهر والهوية البصرية',
    description: 'تحكم بالألوان والخطوط والثيم الافتراضي لتوحيد تجربة المستخدم.',
    fields: [
      { key: 'primaryColor', label: 'اللون الرئيسي', type: 'color', value: '#14746f', defaultValue: '#14746f', note: null, options: null, min: null, max: null },
      { key: 'secondaryColor', label: 'اللون الثانوي', type: 'color', value: '#2f6f9f', defaultValue: '#2f6f9f', note: null, options: null, min: null, max: null },
      { key: 'sidebarColor', label: 'لون الشريط الجانبي', type: 'color', value: '#ffffff', defaultValue: '#ffffff', note: null, options: null, min: null, max: null },
      { key: 'buttonColor', label: 'لون الأزرار', type: 'color', value: '#14746f', defaultValue: '#14746f', note: null, options: null, min: null, max: null },
      {
        key: 'fontFamily',
        label: 'الخط',
        type: 'select',
        value: 'noto',
        defaultValue: 'noto',
        note: null,
        options: [
          { label: 'Noto Sans Arabic', value: 'noto' },
          { label: 'Segoe UI', value: 'segoe' },
          { label: 'Tahoma', value: 'tahoma' },
        ],
        min: null,
        max: null,
      },
      { key: 'baseFontSize', label: 'حجم الخط الأساسي', type: 'number', value: 16, defaultValue: 16, note: null, options: null, min: 12, max: 22 },
      {
        key: 'availableThemes',
        label: 'أكثر من ثيم جاهز',
        type: 'select',
        value: 'classic',
        defaultValue: 'classic',
        note: 'اختر مجموعة الثيمات المتاحة للمسؤولين في الواجهة.',
        options: [
          { label: 'كلاسيكي', value: 'classic' },
          { label: 'هادئ', value: 'soft' },
          { label: 'مكثف', value: 'dense' },
        ],
        min: null,
        max: null,
      },
      {
        key: 'defaultTheme',
        label: 'الثيم الافتراضي',
        type: 'select',
        value: 'classic',
        defaultValue: 'classic',
        note: null,
        options: [
          { label: 'كلاسيكي', value: 'classic' },
          { label: 'هادئ', value: 'soft' },
          { label: 'مكثف', value: 'dense' },
        ],
        min: null,
        max: null,
      },
    ],
  },
  {
    key: 'finance',
    title: 'الإعدادات المالية',
    description: 'سياسات العملة والترقيم وقواعد اعتماد المستندات المالية.',
    fields: [
      { key: 'baseCurrency', label: 'العملة الأساسية', type: 'text', value: 'ريال سعودي', defaultValue: 'ريال سعودي', note: null, options: null, min: null, max: null },
      { key: 'currencySymbol', label: 'رمز العملة', type: 'text', value: 'ر.س', defaultValue: 'ر.س', note: null, options: null, min: null, max: null },
      { key: 'decimalPlaces', label: 'عدد المنازل العشرية', type: 'number', value: 2, defaultValue: 2, note: null, options: null, min: 0, max: 4 },
      {
        key: 'invoiceNumberingMethod',
        label: 'طريقة ترقيم الفواتير',
        type: 'select',
        value: 'prefix-sequence',
        defaultValue: 'prefix-sequence',
        note: null,
        options: [
          { label: 'بادئة + رقم تسلسلي', value: 'prefix-sequence' },
          { label: 'سنة + بادئة + رقم', value: 'year-prefix-sequence' },
        ],
        min: null,
        max: null,
      },
      { key: 'invoicePrefix', label: 'prefix للفواتير', type: 'text', value: 'INV', defaultValue: 'INV', note: null, options: null, min: null, max: null },
      { key: 'paymentPrefix', label: 'prefix للدفعات', type: 'text', value: 'PAY', defaultValue: 'PAY', note: null, options: null, min: null, max: null },
      { key: 'transferPrefix', label: 'prefix للتحويلات', type: 'text', value: 'TRN', defaultValue: 'TRN', note: null, options: null, min: null, max: null },
      { key: 'stockCountPrefix', label: 'prefix للجرد', type: 'text', value: 'STK', defaultValue: 'STK', note: null, options: null, min: null, max: null },
      { key: 'payrollPrefix', label: 'prefix للرواتب', type: 'text', value: 'SAL', defaultValue: 'SAL', note: null, options: null, min: null, max: null },
      { key: 'annualNumbering', label: 'هل الترقيم سنوي أو تراكمي', type: 'boolean', value: true, defaultValue: true, note: 'عند التفعيل يبدأ التسلسل من جديد مع كل سنة مالية.', options: null, min: null, max: null },
      { key: 'allowInvoiceEditAfterApproval', label: 'هل يسمح بتعديل الفاتورة بعد الاعتماد', type: 'boolean', value: false, defaultValue: false, note: null, options: null, min: null, max: null },
      { key: 'archiveInsteadOfDelete', label: 'هل يسمح بالحذف أم الأرشفة فقط', type: 'boolean', value: true, defaultValue: true, note: 'يفضل تفعيل الأرشفة للحفاظ على الأثر المحاسبي.', options: null, min: null, max: null },
    ],
  },
  {
    key: 'cashBank',
    title: 'إعدادات الدرج والبنك',
    description: 'ضوابط جلسات الدرج والحركات النقدية والمرجع البنكي.',
    fields: [
      { key: 'openingBalanceRequired', label: 'هل الرصيد الافتتاحي للدرج إجباري', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'drawerClosingRequired', label: 'هل إغلاق جلسة الدرج إجباري', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'allowDrawerMovementsWithoutSession', label: 'هل يسمح بحركات درج بدون جلسة', type: 'boolean', value: false, defaultValue: false, note: null, options: null, min: null, max: null },
      { key: 'drawerDifferenceAlertLimit', label: 'حد التنبيه على فرق الدرج', type: 'number', value: 25, defaultValue: 25, note: null, options: null, min: 0, max: null },
      { key: 'bankReferenceRequired', label: 'هل المرجع البنكي إجباري', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
    ],
  },
  {
    key: 'inventory',
    title: 'إعدادات المخزون',
    description: 'طريقة التعامل مع الجرد والتحويلات وعرض كميات وتكاليف المخزون.',
    fields: [
      {
        key: 'stockCountMode',
        label: 'هل الجرد للمقارنة فقط أم للتعديل لاحقًا',
        type: 'select',
        value: 'compare',
        defaultValue: 'compare',
        note: null,
        options: [
          { label: 'للمقارنة فقط', value: 'compare' },
          { label: 'يسمح بالتعديل لاحقًا', value: 'adjustable' },
        ],
        min: null,
        max: null,
      },
      { key: 'autoApplyBranchTransfers', label: 'هل التحويل بين الفروع يخصم ويضيف تلقائيًا', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'showCostToUsers', label: 'هل التكلفة تظهر للمستخدمين', type: 'boolean', value: false, defaultValue: false, note: null, options: null, min: null, max: null },
      { key: 'showCurrentQuantity', label: 'هل تعرض الكمية الحالية', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'showIncomingQuantity', label: 'هل تعرض الكمية الواردة', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'showTransferredQuantity', label: 'هل تعرض الكمية المحولة', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
    ],
  },
  {
    key: 'employeesPayroll',
    title: 'إعدادات الموظفين والرواتب',
    description: 'قواعد أرقام الموظفين والرواتب وملفات البصمة.',
    fields: [
      { key: 'employeeNumberFormat', label: 'صيغة رقم الموظف', type: 'text', value: 'EMP-{0000}', defaultValue: 'EMP-{0000}', note: 'مثال: EMP-0001 أو BR-{branch}-{0000}.', options: null, min: null, max: null },
      { key: 'defaultBranchRequired', label: 'هل الفرع الافتراضي مطلوب', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'autoIncludeAdvancesPenalties', label: 'هل السلف والعقوبات تظهر تلقائيًا في شاشة الراتب', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'preventDuplicateMonthlyPayroll', label: 'منع تكرار راتب لنفس الشهر', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'attendanceAllowedFileTypes', label: 'أنواع الملفات المسموح رفعها للبصمة', type: 'text', value: 'csv,xlsx', defaultValue: 'csv,xlsx', note: 'اكتب الامتدادات مفصولة بفواصل.', options: null, min: null, max: null },
      { key: 'attendanceMaxFileSizeMb', label: 'الحد الأقصى لحجم الملف', type: 'number', value: 10, defaultValue: 10, note: null, options: null, min: 1, max: 100 },
    ],
  },
  {
    key: 'access',
    title: 'إعدادات الصلاحيات والوصول',
    description: 'تحكم في مستوى تطبيق الصلاحيات داخل القوائم والإجراءات.',
    fields: [
      { key: 'settingsAdminOnly', label: 'هل الإعدادات محصورة بالأدمن', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'hideMenuItemsByPermissions', label: 'هل إخفاء عناصر القائمة حسب الصلاحيات مفعل', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'restrictActionsByPermissions', label: 'هل الأزرار والإجراءات تتقيد بالصلاحيات', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
    ],
  },
  {
    key: 'notifications',
    title: 'إعدادات التنبيهات',
    description: 'مصادر التنبيه التي تظهر للمستخدمين داخل النظام.',
    fields: [
      { key: 'inAppNotificationsEnabled', label: 'تفعيل التنبيهات داخل النظام', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'supplierInvoiceOverdueAlert', label: 'تنبيه فواتير الموردين المتأخرة', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'drawerDifferenceAlert', label: 'تنبيه فرق الدرج', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'stockCountAlert', label: 'تنبيه الجرد', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'missingPayrollAlert', label: 'تنبيه الرواتب غير المسجلة', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'dueAlertDaysBefore', label: 'عدد الأيام قبل تنبيه الاستحقاق', type: 'number', value: 3, defaultValue: 3, note: null, options: null, min: 0, max: 60 },
    ],
  },
  {
    key: 'exportPrint',
    title: 'إعدادات التصدير والطباعة',
    description: 'خيارات PDF وExcel وتنسيقات التاريخ والوقت في المخرجات.',
    fields: [
      { key: 'pdfCompanyName', label: 'اسم الشركة في PDF', type: 'text', value: '', defaultValue: '', note: null, options: null, min: null, max: null },
      { key: 'showLogoInPrint', label: 'ظهور اللوغو', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'printFooter', label: 'تذييل الطباعة', type: 'textarea', value: 'شكراً لاستخدامكم نظامنا', defaultValue: 'شكراً لاستخدامكم نظامنا', note: null, options: null, min: null, max: null },
      {
        key: 'dateFormat',
        label: 'صيغة التاريخ',
        type: 'select',
        value: 'yyyy-MM-dd',
        defaultValue: 'yyyy-MM-dd',
        note: null,
        options: [
          { label: '2026-04-27', value: 'yyyy-MM-dd' },
          { label: '27/04/2026', value: 'dd/MM/yyyy' },
          { label: '27 أبريل 2026', value: 'arabic-long' },
        ],
        min: null,
        max: null,
      },
      {
        key: 'timeFormat',
        label: 'صيغة الوقت',
        type: 'select',
        value: '24h',
        defaultValue: '24h',
        note: null,
        options: [
          { label: '24 ساعة', value: '24h' },
          { label: '12 ساعة', value: '12h' },
        ],
        min: null,
        max: null,
      },
      { key: 'pdfEnabled', label: 'تفعيل PDF', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
      { key: 'excelEnabled', label: 'تفعيل Excel', type: 'boolean', value: true, defaultValue: true, note: null, options: null, min: null, max: null },
    ],
  },
  {
    key: 'maintenance',
    title: 'النسخ الاحتياطي والصيانة',
    description: 'متابعة حالة النسخ الاحتياطي وإطلاق نسخة يدوية عند الحاجة.',
    fields: [
      {
        key: 'backupType',
        label: 'نوع النسخة',
        type: 'select',
        value: 'manual',
        defaultValue: 'manual',
        note: null,
        options: [
          { label: 'يدوية', value: 'manual' },
          { label: 'مجدولة', value: 'scheduled' },
          { label: 'كاملة', value: 'full' },
        ],
        min: null,
        max: null,
      },
      { key: 'lastBackupStatus', label: 'حالة آخر نسخة', type: 'text', value: 'لا توجد نسخة بعد', defaultValue: 'لا توجد نسخة بعد', note: null, options: null, min: null, max: null },
      { key: 'lastBackupAt', label: 'وقت آخر نسخة', type: 'text', value: 'غير محدد', defaultValue: 'غير محدد', note: null, options: null, min: null, max: null },
    ],
  },
];
