FROM node:22-alpine

WORKDIR /workspace

RUN corepack enable

COPY package.json pnpm-workspace.yaml ./
COPY apps/web/package.json apps/web/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN pnpm install --filter @restaurant-erp/web --frozen-lockfile=false

WORKDIR /workspace/apps/web

CMD ["pnpm", "dev"]
