FROM node:22-alpine

WORKDIR /workspace

RUN corepack enable

COPY package.json pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json
COPY packages/shared/package.json packages/shared/package.json

RUN pnpm install --filter @restaurant-erp/api --frozen-lockfile=false

WORKDIR /workspace/apps/api

CMD ["pnpm", "start:dev"]
